language: php
php:
  - 7.1
  - 7.2
env:
  - GIT_COMMIT_SHA=$TRAVIS_COMMIT
  - GIT_BRANCH=$TRAVIS_BRANCH

install:
  - composer install --dev --no-scripts
script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --whitelist=src/
after_success:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - ./cc-test-reporter after-build --exit-code 0

notifications:
  slack:
    secure: osMFQ0eq0Q3/TLUcS7KwIlkbkiSkD0aj2qtzTXPglDxXbDE66n1K1pQ9e626jXIX4VBJjtVsO27DzunSkrzMQa6d2bscgC1YriJaSLLiI1/BRS3f/rImTAEYrwVlSSPouX0HOkaGQCR6Z0zifXXC2q1SxSYrA96L7cdcczTua8g=
  email: false
